name: feature-flow
on:
  push:
    branches:
      - '**'
      - '!master'
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build:prod
      - name: Test
        run: yarn test
      - name: Lint
        run: yarn lint
      - name: Stylelint
        run: yarn lint:styles
